network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: no
      addresses:
        - 192.168.122.104/24
      routes:
        - to: default
          via: 192.168.122.1
      nameservers:
        addresses: [155.230.10.2, 8.8.8.8]
